### ISSUE TITLE
Is it possible to add another level such as a molecules?

### ISSUE THREAD

**Issue by ingvijonasson** [viljamis/vue-design-system#31]
Or rename the structure hierarchy. Example: rename `/templates` to `/pages`?

**Comment by viljamis** [comment]
@ingvijonasson Compared to Atomic Design, this setup doesn’t include molecule level at all. It’s omitted to help reduce the complexity of the system for its end-users. 

This comes from my personal experience working on different systems projects, where I’ve noticed that it just adds unnecessary overhead and slows down decision making in larger teams. With just elements, patterns and templates this process is much faster since you only need to answer a few questions to determine what type of a component it is.

So for example:

If you wonder whether you should create an Element or a Pattern, ask yourself: “can this be broken down into smaller pieces?” If the answer is yes, there’s a high chance that it should be a Pattern instead of an Element.

In addition, I don’t think “pages” as a name make as much sense as “templates” since they exist to document the layout and structure of a section or the entirety of an interface. So they could be something else than pages too, and hence the name could be misleading.

I will be working on the documentation more soon and also blogging about the usage, but in the mean time this might be helpful:

![structure](https://user-images.githubusercontent.com/671836/36832718-5044d090-1d35-11e8-82bc-7638b429d30c.jpg)

**Comment by ingvijonasson** [comment]
Thank you for the detailed answer @viljamis. I have already read through all the nice documentation and really understand the choices that have been made in the system for making it simple. I am not necessary trying to follow atomic design but just trying to figure out if it is possible to change the naming or add another layer or section when needed.

I found out in the meantime that you can simply add another section in [styleguide.config.js](https://github.com/viljamis/vue-design-system/blob/master/styleguide.config.js#L40) for the styleguide and import them in [system.js](https://github.com/viljamis/vue-design-system/blob/master/src/system.js#L4).

**Comment by viljamis** [comment]
@ingvijonasson yes, naming is something you can definitely tweak to suit your or your team’s workflow. Currently it might require some tweaks to the styleguide styles as well tho, but I will simplify the logic there as soon as I find time. In the meantime, maybe this is worth some documentation, do you think? At least giving guidelines on how to change the naming of things (if wanted/needed)?

**Comment by ingvijonasson** [comment]
I think it is well worth in the documentation. What is missing is simply that:

- it is possible to change the names and add more sections
- how it is done

I can help out with this.

**Comment by viljamis** [comment]
@ingvijonasson Still willing to help out with the documentation? :-)

**Comment by viljamis** [comment]
I’ll close this one for now since it isn’t really an issue, but more of an documentation question! Let me know if you want to re-open.
