### ISSUE TITLE
Add tabs option to the docs component 

### ISSUE THREAD

**Issue by chrisroselli** [viljamis/vue-design-system#95]
Would be cool to have the option to add tabs to the `<docs>` component, unless there is already a way to do this.

**Comment by viljamis** [comment]
@chrisroselli Just returned from a 5 week “offline” trip, hence the little delay here. Sorry about that! Can you describe a little bit more what you mean?

**Comment by viljamis** [comment]
I will close this for now as I don’t understand the description :)

**Comment by andywd7** [comment]
I'm not sure if this is what @chrisroselli is talking about but my view would be it would be cool to be able to do similar to [Carbon's style](http://www.carbondesignsystem.com/components/button/code). So that you can split Code | Design | Usage or Code | Usage.

[Clarity](https://vmware.github.io/clarity/documentation/v0.13/buttons) do similar as well or [Hudl](http://uniform.hudl.com/components/buttons/button/design)
